version: "1.0"

services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      POSTGRES_DB: CatalogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  
  basketdb:
    container_name: basketdb
    image: postgres
    environment:
      POSTGRES_DB: BasketDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
    
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  
  catalog.api:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=${POSTGRES_UID};Password=${POSTGRES_PSW};Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PSW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        
  basket.api:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__Database=Server=basketdb;Port=5433;Database=BasketDb;User Id=${POSTGRES_UID};Password=${POSTGRES_PSW};Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PSW}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${HOME}/.aspnet/https:/https:ro
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

volumes:
  postgres_catalog:
