version: "1.0"

services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      POSTGRES_DB: CatalogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

volumes:
  postgres_catalog:
